changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
template: |
  ## Release v$RESOLVED_VERSION 🚀

  ## Breaking Changes 🛠
  $CHANGES_BY_CATEGORY(Breaking Changes 🛠)

  ## Exciting New Features 🎉
  $CHANGES_BY_CATEGORY(Exciting New Features 🎉)

  ## Other Changes
  $CHANGES_BY_CATEGORY(Other Changes)

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## New Contributors 👏
  $CONTRIBUTORS

  Thank you to all our contributors for making this release possible!
